name: Try current plugin with older vault version
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run vault container detached
        run: docker run -d hashicorp/vault:1.2.7

      - name: Copy binary and kill container
        run: ./copy-kill.sh
        working-directory: plugins/vault-plugin-secrets-mock 

      - name: Build binary
        run: make build
        working-directory: plugins/vault-plugin-secrets-mock 

      - name: Start vault dev mode
        run: ./vault-bin server -dev -dev-root-token-id=root -dev-plugin-dir=./vault/plugins &
        working-directory: plugins/vault-plugin-secrets-mock 

      - name: Enable vault plugin
        run: ./vault-bin secrets enable -path=mock-secrets vault-plugin-secrets-mock
        working-directory: plugins/vault-plugin-secrets-mock 

            - name: Test write
        run: VAULT_ADDR=http://127.0.0.1:8200&&./vault-bin write mock-secrets/test message="Hello World"
        working-directory:

      - name: Test read
        run: VAULT_ADDR=http://127.0.0.1:8200&&./vault-bin read mock-secrets/test
        working-directory:
