name: Try current plugin with older vault version
on:
  push:
    branches:
      - master

jobs:
  try:
    strategy:
      matrix:
        vault:
          [
            "vault:1.2.7",
            "vault:1.3.10",
            "vault:1.4.7",
            "vault:1.5.9",
            "vault:1.6.7",
            "vault:1.8.5",
            "vault:1.9.0",
            "vault:latest",
          ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugins/vault-plugin-secrets-mock
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run vault container detached
        run: docker run -d hashicorp/${{ matrix.vault }}

      - name: Copy binary and kill container
        run: ./copy-kill.sh

      - name: Build binary
        run: make build

      - name: memlock the binary
        run: setcap cap_ipc_lock=+ep vault/plugins/vault-plugin-secrets-mock

      - name: Vault address variable
        uses: myci-actions/export-env-var@1
        with:
          name: VAULT_ADDR
          value: http://127.0.0.1:8200

      - name: Start vault dev mode
        run: ./vault-bin server -dev -dev-root-token-id=root -dev-plugin-dir=./vault/plugins &

      - name: Enable vault plugin
        run: ./vault-bin secrets enable -path=mock-secrets vault-plugin-secrets-mock

      - name: Test write
        run: ./vault-bin write mock-secrets/test message="Hello World"

      - name: Test read
        run: ./vault-bin read mock-secrets/test
