name: Try current plugin with older vault version
on:
  push:
    branches:
      - master

jobs:
  try:
    strategy:
      matrix:
        vault:
          [
            "vault:1.2.7",
            "vault:1.3.10",
            "vault:1.4.7",
            "vault:1.5.9",
            "vault:1.6.7",
            "vault:1.8.5",
            "vault:1.9.0",
            "vault:latest",
          ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugins/vault-plugin-secrets-mock
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build binary
        run: make build

      - name: memlock the binary
        run: sudo setcap cap_ipc_lock=+ep vault/plugins/vault-plugin-secrets-mock

      - name: Run vault container
        run: ./run_docker.sh ${{ matrix.vault }}

      - name: Vault address variable
        uses: myci-actions/export-env-var@1
        with:
          name: VAULT_ADDR
          value: http://127.0.0.1:8200

      - name: Enable vault plugin
        run: docker exec notary /bin/sh -c "vault secrets enable -path=mock-secrets vault-plugin-secrets-mock""vault secrets enable -path=mock-secrets vault-plugin-secrets-mock"

      - name: Test write
        run: docker exec notary /bin/sh -c "vault write mock-secrets/test message='Hello World'"

      - name: Test read
        run: docker exec notary /bin/sh -c "vault read mock-secrets/test"
